### ISSUE TITLE
logmanager 2.3.5 broken java.lang.OutOfMemoryError: Java heap spac

### ISSUE THREAD

**Issue by adirkola** [aws-greengrass/aws-greengrass-log-manager#210]
hey my name is Adir and i working with Greengrass 

I am using logmanager ver 2.3.5
and I get this error.
2023-08-14T11:04:34.560Z [ERROR] (pool-2-thread-34) com.aws.greengrass.logmanager.LogManagerService: service-errored. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}                        
java.lang.OutOfMemoryError: Java heap space

I did several things I changed the heap max size from 
1. The nucleus configuration to 256m didn't help
2. from Greengrass.service added their environment
Environment="_JAVA_OPTIONS=-Xmx256m"
but didn't help
This is kind of urgent because the production is down and we don't have a lot of a place in the device  and can't run it without a log manager that uploads the logs to the cloud 
Thanks a lot.

**Comment by MikeDombo** [comment]
Hello,

Please list all components you have installed. Please also provide the precise configuration you have set. If you're running out of memory, then do not limit the amount of memory that Java is allowed to use.

**Comment by MikeDombo** [comment]
No response, closing for now. Reopen as needed.
