### ISSUE TITLE
Manage Cloudwatch log group retention time

### ISSUE THREAD

**Issue by HaimMyasnikoff** [aws-greengrass/aws-greengrass-log-manager#220]
Now log group Retention time set as **Never expired** by default.

Is it possible to change it to e.g. 90 days during log group creation via Greengrass component?

**Comment by MikeDombo** [comment]
Hi Haim,

No this is not possible with this component, but you can absolutely do that by calling the appropriate APIs for CloudWatch in your own component, cloudformation, or other solutions. All CloudWatch log groups do not expire by default.

**Comment by HaimMyasnikoff** [comment]
@MikeDombo 

what will be a component behavior , if log group will be created with some parameters (Rotation is one of them) before first component's start?

will be log group recreated with default component's parameters?

**Comment by MikeDombo** [comment]
This component creates the log group if it does not exist. If the log group already exists then this component will not change any settings of that log group.

**Comment by HaimMyasnikoff** [comment]
@MikeDombo 

Thanks for clear and fast replies!
