### ISSUE TITLE
(LogManager): Consider uploading active log file

### ISSUE THREAD

**Issue by fiLLLip** [aws-greengrass/aws-greengrass-log-manager#51]
**Feature Description**
This line skips the active log file for some reason. Why? We wasted an entire day on debugging why the current logs did not upload.

https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/e52b9d120521ebb06205a273b8349015669252e0/src/main/java/com/aws/greengrass/logmanager/LogManagerService.java#L513

**Use Case**
Getting "real time" logs up in CloudWatch.

**Proposed Solution**
Remove this line to enable uploading of partial active logs. It looks like the partial upload is in place already.

**Other**

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by jordanjennings** [comment]
In the short term the documentation should be updated to indicate that logs are not uploaded until the file is rotated, because I also wasted some time trying to figure out why logs were not uploading.

But that's just a band-aid for the real problem - I think all users expect logs to be shipped in (near) real-time.

**Comment by mora0136** [comment]
I would like to see this become a feature of this component, I can help in getting that available. Are there any blockers for this? It has been a year with no solution suggested so I am cautious to start work in case there is a known reason why this can't be done.

**Comment by vcarnogu** [comment]
Any plans to implement it? Not having the current file when troubleshooting remotely is a pain.

**Comment by Nelsonochoam** [comment]
Hi all -- we just released support for uploading the active log file with Log Manager 2.3.0 https://docs.aws.amazon.com/greengrass/v2/developerguide/greengrass-release-2022-11-18.html
