### ISSUE TITLE
PutLogEvents request cannot span more than 24 hours

### ISSUE THREAD

**Issue by kris-sum** [aws-greengrass/aws-greengrass-log-manager#59]
**Describe the bug**
There appears to be a problem uploading a log file that hasn't rotated properly? 

**To Reproduce**
Not sure how to reproduce, I had to delete the rotated logs on a production device to get it up and running again quickly

**Expected behavior**

**Actual behavior**
com.aws.greengrass.logmanager.CloudWatchLogsUploader: Unable to upload 1450 logs to /aws/greengrass/GreengrassSystemComponent/eu-west-2/System-/2021/05/17/thing/*REDACTED*. {}

software.amazon.awssdk.services.cloudwatchlogs.model.InvalidParameterException: **The batch of log events in a single PutLogEvents request cannot span more than 24 hours.** (Service: CloudWatchLogs, Status Code: 400, Request ID: e3ce483a-abc5-41ac-bfca-70b730d29345, Extended Request ID: null)

**Environment**
 - OS: Ubuntu 20.04.2 LTS (focal)
 - JDK version:
 - Nucleus version: 2.1.0 
 - Log Manager version: 2.1.0

**Comment by MikeDombo** [comment]
Hi and thank you very much for reporting the issue to us. We'll have a look and try to get this bug fixed ASAP.

**Comment by MikeDombo** [comment]
Fixed by #62
