### ISSUE TITLE
(aws.greengrass.LogManager): allow for multiple  log manager component configuration deployed to the same device to be merged

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-log-manager#65]
**Feature Description**
Defines the `componentLogsConfiguration` field inside `logsUploaderConfiguration` as a map instead of an array, allowing for `componentLogsConfiguration` to be merged across deployments

**Use Case**
A device can be targeted by multiple independent deployments. Each deployment might add new components and user wish to configure aws.greengrass.LogManager for such components. Currently, the `componentLogsConfiguration` is specified as an array, which is not merged, meaning that the last deployment applied to the device will determine the effective component configuration.

**Proposed Solution**
1. Change the `componentLogsConfiguration` to a map of configuration objects
2. `componentName` is now specified as the key in the map
3. removed `componentName` from the allowed fields in the component log configuration object

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Merged in 2.2.0
